FROM ubuntu:latest

RUN mkdir server

WORKDIR /server

COPY ./backend/req.txt /server/req.txt

COPY ./backend/script.py /server/script.py

RUN apt-get update -y && \
	apt-get install -y python-pip python-dev

RUN apt-get install libmysqlclient-dev -y && \
	pip install mysqlclient && \
	pip install -r req.txt

EXPOSE 5000
ENTRYPOINT ["python"]
CMD ["script.py"]
 


