apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: flask-deployment 
  labels:
    app: flask 
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: flask 
  template: 
    metadata: 
      labels: 
        app: flask 
    spec: 
      containers: 
      - name: flask 
        image: mgarkel/backend_hw3:latest
        ports: 
        - containerPort: 5000 